# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  jwt_secret: 7777777seven7777777
  jwt_algorithm: HS512
  secret_key_base: a8285bb43d1fc9657a042c4c57e3b2cb05ec6b0467f25330c1b05d61533b8d16bfd6e212c22459f3b6841ce1986a0a9469116d98f00133d17ef5be9dc2218e0b

test:
  jwt_secret: 7777777seven7777777
  jwt_algorithm: HS512
  secret_key_base: a8285bb43d1fc9657a042c4c57e3b2cb05ec6b0467f25330c1b05d61533b8d16bfd6e212c22459f3b6841ce1986a0a9469116d98f00133d17ef5be9dc2218e0b
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  jwt_secret: 7777777seven7777777
  jwt_algorithm: HS512
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging:
  jwt_secret: 7777777seven7777777
  jwt_algorithm: HS512
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
