class AddMissingIndexes2 < ActiveRecord::Migration[5.0]
  def change
    add_index :social_logs, [:created_at]
    add_index :social_logs, [:updated_at]
    add_index :social_accounts, [:provider]
    add_index :social_accounts, [:created_at]
    add_index :social_accounts, [:updated_at]
    add_index :social_accounts, [:bdate_day]
    add_index :social_accounts, [:bdate_month]
    add_index :social_accounts, [:bdate_year]
    add_index :client_accounting_logs, [:created_at]
    add_index :client_accounting_logs, [:updated_at]
    add_index :locations, [:created_at]
    add_index :locations, [:updated_at]
    add_index :client_devices, [:created_at]
    add_index :client_devices, [:updated_at]
    add_index :clients, [:created_at]
    add_index :clients, [:updated_at]
    add_index :post_auth_logs, [:created_at]
    add_index :post_auth_logs, [:updated_at]
    add_index :client_counters, [:created_at]
    add_index :client_counters, [:updated_at]
  end
end
